### ISSUE TITLE
非常喜欢老大的博客系统，用了之后想给老大下次更新提几点建议

### ISSUE THREAD

**Issue by xzyone** [pantsPoi/Spruche#2]
1.希望老大抽空将站点设置页面更新一下，希望能包括站点名称、meta标签、博主头像、昵称、统计代码等的快捷设置；可以修改后台管理页面的地址；
2.希望可以优化下后台的菜单栏设置成可收起的那种，方便手机端更新。

另外希望这个系统越来越好，以后能不断完善，友情链接、about、留言等面板不断整合到后台管理面板，逐步形成一个完整的博客系统。我也会趁业余时间多学下nodejs代码，希望有一天能帮助老大完善系统

**Comment by IceEnd** [comment]
在下会抽空慢慢填完这些坑，dalao请耐心等待。
