### ISSUE TITLE
首页可以添加类似/index这样访问么

### ISSUE THREAD

**Issue by xzyone** [pantsPoi/Spruche#3]
是这样的，我在网页加了播放器，安装在了foot.html(http://xzy.one)，进入文章、留言板这些页面播放器都可以继续播放，但点击头部头像和home按钮就会进入首页http://xzy.one/，相当于重新打开了网页，播放器就会重新加载歌曲。所以请问能不能通过修改几个文件定义除了http://xzy.one/是首页之外，比如http://xzy.one/index也可以是首页，类似于一个html网站 / 和/index.html 都显示的是首页。麻烦哥能不能有空回复下我修改哪几个文件完成这样的设置，感谢！

**Comment by LanlingKira** [comment]
>第一个问题，在你需要的a标签里添加属性值**data-pjax="true"**就可以实现pjax加载，例如
```html
<a href="xxx" data-pjax="true">xxx</a>
```
>你需要的效果应该修改header.html文件就可以实现了。
>第二个问题，自定义首页地址，可以修改routes\index.js文件，在底部的module.exports = router;之前增加
```js
router.get('/index', function (req, res, next) {
  var blogs, website, amount = 0;
  websiteDao.getWebSite()
    .then(function (result) {
      website = result[0];
      return blogsDao.getBlogByPage(0, 10);
    })
    .then(function (result) {
      res.render('front/index', { website: website, blogs: result });
    })
    .catch(function (error) {
      res.render('error', { message: '404', error: error });
    })
});
```
>router.get('/index'……相当于是你要自定义的链接，res.render('front/index'……是你的主页文件地址。
添加其他页面
```js
router.get('/example', function (req, res, next) {
  websiteDao.getWebSite()
    .then(function (result) {
      res.renderPjax('front/example', { website: result[0] });
    })
    .catch(function (error) {
      res.render('error', { message: 404, error: error });
    });
});
```
(๑•̀ㅂ•́)و✧

**Comment by xzyone** [comment]
@LanlingKira @IceEnd 完美解决，大神们请受我一拜！

**Comment by xzyone** [comment]
其实第二个我想到了0.0，然后我把代码改成了这样:
router.get(**"/"||'/index',** function (req, res, next) {
  var blogs, website, amount = 0;
  websiteDao.getWebSite()
    .then(function (result) {
      website = result[0];
      return blogsDao.getBlogByPage(0, 10);
    })
    .then(function (result) {
      res.render('front/index', { website: website, blogs: result });
    })
    .catch(function (error) {
      res.render('error', { message: '404', error: error });
    })
});


是不是脑洞很大O(∩_∩)O~

**Comment by xzyone** [comment]
新问题又来了，第一种那样修改的话，播放器正常了，但文章加载不出来了0.0
[](http://xzy.one)

**Comment by xzyone** [comment]
http://xzy.one

**Comment by LanlingKira** [comment]
首页有个加载特效，进入首页时自动触发这个事件，滚轮滚动也会触发。之后通过pjax加载时没有触发这个事件，文章数量过少不会出现滚动条，也无法触发滚轮事件。

**Comment by xzyone** [comment]
也就是说文章数多了之后就自动好了？
